spring.application.name=Peso_granja

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=${PORT:8080}
app.jwt.secret=4Ky7KLP1RrJs7uSfwBG1Q21mMDxSTrFrmIWL1I3R+LA=
app.jwt.expiration-seconds=900
app.jwt.issuer=piyosoft